[package]
name = "fragarach"
version = "0.0.0"
edition = "2021"

description = "Modular OSINT framework for blockchain forensics and investigations"
license = "MIT"
repository = "https://github.com/BD14734/fragarach"

[dependencies]
